changelog:
  categories:
    - title: ⚠️ BREAKING CHANGES
      labels:
        - breaking
    - title: 🤩 New Features
      labels:
        - feature
    - title: 🗞️ Improvements
      labels:
        - enhancement
    - title: 🛠️ Bug Fixes
      labels:
        - fix
        - bugfix
    - title: 🧹 Maintenance
      labels:
        - chore
        - documentation
        - dependencies
        - misc
    - title: 👀 Other Changes
      labels:
        - '*'
